services:
  client:
    build: .
    container_name: tutorit_client
    environment:
      REACT_APP_SERVER_ADDRESS: "https://mesharaserver.win"
    networks:
      - tutorit-net
    depends_on:
      tutorit_server:
    ports:
      - "3000:80"

networks:
  tutorit-net:
    external: true
