services:
  client:
    build: .
    container_name: tutorit_client
    environment:
      REACT_APP_SERVER_ADDRESS: "http://tutorit_server:9000"
    networks:
      - tutorit-net
    depends_on:
      - tutorit-server
    ports:
      - "3000:80"

networks:
  tutorit-net:
    external: true
