export const SET_CALL_PARTNER_USERNAME = 'SET_CALL_PARTNER_USERNAME';

export const SET_GLOBAL_LANGUAGE = 'SET_GLOBAL_LANGUAGE';

export const COURSE_APPLICATION_SUCCESS = 'COURSE_APPLICATION_SUCCESS';
